name: Build & Test

# this is triggered on push to the repository
on: [push, pull_request]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
            - uses: pre-commit/action@v3.0.0
    build:
        name: 'Build and Test'
        needs: [pre-commit]
        runs-on: 'ubuntu-latest'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '17'
            - run: npm install
            - run: npm run build
